### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by rushabhsooni** [kjam/wswp#1]
pls give details about the python version and virtual environment - and packages

**Comment by mcrouse911** [comment]
Pyhton 3 recent version
trying to use Pycharm or Sublime

Thank you for responding

**Comment by rushabhsooni** [comment]
i have pycharm and  pyhton 3.6 and dependencies

**Comment by mcrouse911** [comment]
Pycharm and Python 3.6 please

**Comment by kjam** [comment]
Hi there,

If you follow along in the book, I install packages as they are needed. I used Python 3.6, but everything should work with Python 3.4+. Off the top of my head you will need:

```selenium
requests
lxml
bs4
scrapy
```

and a few others that are more difficult to install like Portia and PyQt. The installation instructions are all in the book, however, and I talk about how to install everything in there! :)

-kj
