### ISSUE TITLE
Skipping due to the depth

### ISSUE THREAD

**Issue by ramapitecusment** [kjam/wswp#4]
As i understand you changed to way the Web Site works. in book there are http://example.webscraping.com/view/Afghanistan-1, however now http://example.webscraping.com/places/default/view/Afghanistan-1. I am a biggener, therefore faced with problem: 
Downloading: http://example.webscraping.com/places/default/index
Skipping http://example.webscraping.com/places/default/index/1 due to depth
Skipping http://example.webscraping.com/places/default/view/Antigua-and-Barbuda-10 due to depth
Skipping http://example.webscraping.com/places/default/view/Antarctica-9 due to depth
Skipping http://example.webscraping.com/places/default/view/Anguilla-8 due to depth
Skipping http://example.webscraping.com/places/default/view/Angola-7 due to depth
Skipping http://example.webscraping.com/places/default/view/Andorra-6 due to depth
Skipping http://example.webscraping.com/places/default/view/American-Samoa-5 due to depth
Skipping http://example.webscraping.com/places/default/view/Algeria-4 due to depth
Skipping http://example.webscraping.com/places/default/view/Albania-3 due to depth
Skipping http://example.webscraping.com/places/default/view/Aland-Islands-2 due to depth
Skipping http://example.webscraping.com/places/default/view/Afghanistan-1 due to depth
Skipping http://example.webscraping.com/places/default/user/login?_next=/places/default/index due to depth
Skipping http://example.webscraping.com/places/default/user/register?_next=/places/default/index due to depth
Skipping http://example.webscraping.com/places/default/index due to depth

THE CODE .TXT
P.S. PyCharm, Python 3.6.3. If you have newer edition of book, pleaser give me some information, I will be very thankful!!!
[final.txt](https://github.com/kjam/wswp/files/1411706/final.txt)

**Comment by HeJiaJunPan** [comment]
link_crawler(start_url, link_regex, max_depth=1)

Please change value of "max_depth".Your setting value is too small.

**Comment by kjam** [comment]
Hi there,

Thanks for this issue. Can you let me know what page this was on? Thanks!

-katharine
