### ISSUE TITLE
There are many problems with the sample website.

### ISSUE THREAD

**Issue by liaoran** [kjam/wswp#9]
Hi,through the practice of the first chapter of the fourth quarter code found that using the sample website, the results of the code running and the code in the book run completely inconsistent, please modify the original author as soon as possible, thank you!

**Comment by kjam** [comment]
Hi @liaoran ,

I don't have access to the example site, but have contacted the author who maintains it. Please see the fixes in this repository (or this fix: https://github.com/kjam/wswp/issues/5#issuecomment-346592299)

Thanks!
-katharine
